project:
  type: book
  output-dir: docs  # 输出目录, 生成的 HTML 文件会放在 docs 目录下

book:
  title: "ACCA F9（财务管理）"
  reader-mode: true
  author: "叶会"
  date: today
  date-format: iso
#  lang: zh  # 不要设置这个，会导致很多问题
  
  sidebar:    # 侧边栏配置
    title: "ACCA F9（财务管理）"
    logo: images/book-logo.png
    logo-href: https://yehuiapple.github.io/ACCA-/
    style: floating
    search: true
    tools:
      - icon: github
        href: https://github.com/yehuiapple/quarto_book

  favicon: images/book-logo.png   # URL logo
  site-url: https://yehuiapple.github.io/ACCA-/ # 主页地址, 否则点击右上角链接会乱码
  editor: source    # 始终采用源代码模式编辑

#----------------------- Chapters ---------------
  chapters:

    - index.qmd

    - part: "Introduction"
      chapters:
        - body/Introduction.md

    - part: "**A: Financial Management Function**"
      chapters:
        - body/1 Financial Management Function.md

    - part: "**B: Financial Management Environment**"
      chapters:
        - body/2 Financial Management Environment.md

    - part: "**C: Working Capital Management**"
      chapters:
        - body/3 Working Capital Management.md
        - body/4 Cash Management and Working Capital Finance.md

    - part: "**D: Investment Appraisal**"
      chapters:
        - body/5 Investment Decision.md
        - body/6 Allowing for Inflation and Taxation.md
        - body/7 Project Appraisal under Risk.md
        - body/8 Specific Investment Decision.md

    - part: "**E: Business Finance**"
      chapters:
        - body/9 Source of Finance.md
        - body/10 Dividend Policy.md
        - body/11 the Cost of Capital.md
        - body/12 Gearing and Capital Structure.md

    - part: "**F: Business Valuations**"
      chapters:
        - body/13 Business Valuation.md

    - part: "**G: Risk Management**"
      chapters:
        - body/14 Foreign Currency Risk.md
        - body/15 Interest Rate Risk.md

#    - part: "Answers"
#      chapters:
#        - body/Answers_ABC.md
#        - body/Answers_D.md
#        - body/Answers_E.md
#        - body/Answers_F.md
#        - body/Answers_G.md

    - part: "Appendix"
      chapters:
        - body/Appendix.md

format:
  html:
    toc: true            # 启用页面内目录
    toc-depth: 3         # 显示 Chapter → H3 节标题（不显示 1.1 子节）
    theme: cosmo         # 可选：cosmo, flatly, litera, litera, yeti 等  主题模版
    linestretch: 1.6          # 行间距
    fontsize: 11.5pt          # 字号
    number-sections: false    # 关闭自动编号（章节已有自定义编号）
    link-external-newwindow: true
    highlight: true            # 代码高亮
    highlight-style: atom-one  # 语法高亮, atom-one, breezy, github, tango, solarized-light
    code-fold: false           # （可选）代码默认不折叠
    code-line-numbers: false   # （可选）关闭行号
    code-overflow: wrap        # 控制长代码的换行   
    css: styles.css
    callout-appearance: default        # 启用 callout 默认渲染样式
    md-extensions:
      - callout                        # 确保 markdown 支持 callout 块语法
editor: visual

